### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by ShaharEli** [yaronlev9/Ticket-Manager#5]
You can hide the restore button and count of hidden tickets if the count is 0 it will look better

**Comment by Cyber4sPopo** [comment]
This is a good point. When there is nothing to "restore", when that button is not relevant, we don't have to show it.
It makes a smoother experience to hide non useful elements from the user to prevent confusion.

> You can hide the restore button and count of hidden tickets if the count is 0 it will look better
